apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world
    image: busybox
    command: ['sh', '-c', 'echo Hello, Universe! I hope this works. && sleep 3600']
